class PersistentStore:
    def __init__(self, db_path: Path, faiss_index_path: Path): ...
    def enqueue_pending(self, filepath: Path, suggestions: List[Tuple[Path,float]]): ...
    def dequeue_feedback(self) -> List[FeedbackItem]: ...
    def save_model(self, engine_name: str, artifact_path: Path) -> None: ...
